// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnixBusinessErpApp;

namespace OnixBusinessErpApp.Its.Onix.Erp.Migrations
{
    [DbContext(typeof(OnixErpDbContextPgSql))]
    [Migration("20190922084504_Masters11")]
    partial class Masters11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Its.Onix.Erp.Models.Generals.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int?>("CustomerGroupMasterId");

                    b.Property<int?>("CustomerTypeMasterId");

                    b.Property<string>("Description");

                    b.Property<string>("Key");

                    b.Property<DateTime>("LastMaintDate");

                    b.Property<string>("Name");

                    b.Property<int?>("NamePrefixMasterId");

                    b.Property<string>("Tag");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerGroupMasterId");

                    b.HasIndex("CustomerTypeMasterId");

                    b.HasIndex("NamePrefixMasterId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Its.Onix.Erp.Models.Generals.Master", b =>
                {
                    b.Property<int>("MasterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Description");

                    b.Property<string>("Key");

                    b.Property<DateTime>("LastMaintDate");

                    b.Property<string>("Name");

                    b.Property<string>("Tag");

                    b.HasKey("MasterId");

                    b.ToTable("Masters");
                });

            modelBuilder.Entity("Its.Onix.Erp.Models.Generals.Customer", b =>
                {
                    b.HasOne("Its.Onix.Erp.Models.Generals.Master", "CustomerGroup")
                        .WithMany()
                        .HasForeignKey("CustomerGroupMasterId");

                    b.HasOne("Its.Onix.Erp.Models.Generals.Master", "CustomerType")
                        .WithMany()
                        .HasForeignKey("CustomerTypeMasterId");

                    b.HasOne("Its.Onix.Erp.Models.Generals.Master", "NamePrefix")
                        .WithMany()
                        .HasForeignKey("NamePrefixMasterId");
                });
#pragma warning restore 612, 618
        }
    }
}
